'\" t
.\"     Title: nix-worker
.\"    Author: Eelco Dolstra
.\" Generator: DocBook XSL-NS Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: May 2012
.\"    Manual: Command Reference
.\"    Source: Nix 1.0
.\"  Language: English
.\"
.TH "NIX\-WORKER" "8" "May 2012" "Nix 1\&.0" "Command Reference"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nix-worker \- Nix multi\-user support daemon
.SH "SYNOPSIS"
.HP \w'\fBnix\-worker\fR\ 'u
\fBnix\-worker\fR \fB\-\-daemon\fR
.SH "DESCRIPTION"
.PP
The Nix daemon is necessary in multi\-user Nix installations\&. It performs build actions and other operations on the Nix store on behalf of unprivileged users\&.
.SH "AUTHOR"
.PP
\fBEelco Dolstra\fR
.br
LogicBlox
.RS 4
Author
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2004-2012 Eelco Dolstra
.br
